### ISSUE TITLE
MDN link about accessible progress bars is broken

### ISSUE THREAD

**Issue by greglockwood** [css-for-js/mini-component-library#17]
The existing link in the `README.md` to `https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role` no longer works.

The closest equivalent I found - after digging around for a bit - is:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role

I would have created a PR to fix this, but I figure it is easier for you to just change it, @joshwcomeau. 😅  I should say, it's easier for _me_ to just ask you to change it. 😁 

The corresponding link in the [course solution page](https://courses.joshwcomeau.com/css-for-js/03-components/18-workshop-progress) for the progressbar component also needs to change.

**Comment by joshwcomeau** [comment]
Sorry for the delay! This should be fixed now :)
